version: 0.0
os: linux
files:
  - source: /
    destination: /deployments
hooks:
  ApplicationStart:
    - location: scripts/startservice.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/stopservice.sh
      timeout: 300
      runas: root