version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.0
        
    steps:
      - checkout
      - run: mvn clean package
      - run: mvn verify sonar:sonar

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: mvn clean package
      - run: mvn verify sonar:sonar
      - heroku/deploy-via-git

workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy
