version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk

    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: false

      # build and push Docker image
      - run: mvn clean package
      - run: sudo rm -f ~/.docker/config.json
      - run: |
          docker build -t $DOCKERHUB_USER/studentapi .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker push $DOCKERHUB_USER/studentapi
          sudo rm -f ~/.docker/config.json
          docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
          docker build --rm=false -t registry.heroku.com/dchacko-studentapi/studentapi .
          docker push registry.heroku.com/dchacko-studentapi/studentapi:latest

workflows:
  build-test-deploy:
    jobs:
      - build:
          context:
            - Heroku
