version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # build and push Docker image
      - run: ./mvnw clean install
      - run: apk add docker-cli
      - run: |
          docker build -t spring-security/studentapi .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
          docker push spring-security/studentapi
