version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run: mvn clean package
      - run: mvn verify sonar:sonar
      - heroku/deploy-via-git

workflows:
  build-test-deploy:
    jobs:
      - deploy
