openapi: 3.0.0
info:
  title: Student API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/v1/student/list:
    get:
      summary: Retrieve All Students
      tags:
        - Student
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Student'
              examples:
                example-1:
                  value:
                    - id: 1
                      firstName: John
                      lastName: Doe
                    - id: 2
                      firstName: Jane
                      lastName: Doe
        '500':
          description: Internal Server Error
      operationId: get-v1-student-list
      description: Retrieve a list of all the students
    parameters: []
  /api/v1/student:
    post:
      summary: Add a new student
      operationId: post-v1-student
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
              examples:
                example-1:
                  value:
                    id: 1
                    firstName: John
                    lastName: Doe
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      description: Add a new Student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
            examples:
              example-1:
                value:
                  firstName: John
                  lastName: Doe
      tags:
        - Student
    parameters: []
    put:
      summary: Update a student
      operationId: put-api-v1-student
      responses:
        '200':
          description: OK
      description: Update details for a single student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
        description: ''
      security:
        - OAuth2:
            - StudentService-Client1-Scope
      tags:
        - Student
  '/api/v1/student/{studentId}':
    delete:
      summary: Delete a student
      operationId: 'delete-v1-student-:studentId'
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: Delete a student
      tags:
        - Student
    parameters:
      - schema:
          type: integer
        name: studentId
        in: path
        required: true
    get:
      summary: Get Student By Id
      operationId: get-api-v1-student-studentId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
      security:
        - OAuth2:
            - StudentService-Client1-Scope
      description: Retrieve details for a single student
      tags:
        - Student
components:
  schemas:
    Student:
      title: Student
      type: object
      x-examples:
        example-1:
          id: 123
          firstName: John
          lastName: Doe
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: 'http://localhost:9080/auth/realms/MicroServices/protocol/openid-connect/token'
          refreshUrl: ''
          scopes:
            StudentService-Client1-Scope: Client1's scope
          authorizationUrl: 'http://localhost:9080/auth/realms/MicroServices/protocol/openid-connect/auth'
tags:
  - name: Student
security:
  - OAuth2:
      - StudentService-Client1-Scope
